"""add_available_quantity_to_supplier_prices

Revision ID: b022997f60de
Revises: a2031a0aba08
Create Date: 2026-02-27 14:48:23.741067

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b022997f60de'
down_revision: Union[str, None] = 'a2031a0aba08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_invoices_invoice_number'), table_name='supplier_invoices')
    op.drop_table('supplier_invoices')
    op.drop_index(op.f('ix_supplier_users_email'), table_name='supplier_users')
    op.drop_table('supplier_users')
    op.drop_table('supplier_responses')
    op.drop_index(op.f('ix_supplier_invitations_invite_token'), table_name='supplier_invitations')
    op.drop_table('supplier_invitations')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_shipments_shipment_number'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_table('shipment_items')
    op.drop_table('supplier_price_updates')
    op.add_column('supplier_prices', sa.Column('available_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_prices', 'available_quantity')
    op.create_table('supplier_price_updates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('current_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('proposed_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('change_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='priceupdatestatus'), autoincrement=False, nullable=False),
    sa.Column('reviewed_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('review_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('supplier_price_updates_product_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('supplier_price_updates_supplier_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('supplier_price_updates_pkey'))
    )
    op.create_table('shipment_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('shipment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('po_line_item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity_shipped', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['po_line_item_id'], ['po_line_items.id'], name=op.f('shipment_items_po_line_item_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('shipment_items_shipment_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('shipment_items_pkey'))
    )
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('po_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('shipment_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('shipment_type', postgresql.ENUM('full', 'partial', name='shipmenttype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('preparing', 'dispatched', 'in_transit', 'delivered', 'cancelled', name='shipmentstatus'), autoincrement=False, nullable=False),
    sa.Column('carrier', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tracking_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tracking_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estimated_delivery', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('actual_delivery', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('dispatched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('shipments_po_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('shipments_pkey'))
    )
    op.create_index(op.f('ix_shipments_shipment_number'), 'shipments', ['shipment_number'], unique=True)
    op.create_table('invoice_line_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('invoice_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('po_line_item_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tax_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('po_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('po_unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantity_match', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('price_match', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['supplier_invoices.id'], name=op.f('invoice_line_items_invoice_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['po_line_item_id'], ['po_line_items.id'], name=op.f('invoice_line_items_po_line_item_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('invoice_line_items_pkey'))
    )
    op.create_table('supplier_invitations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('invite_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'accepted', 'expired', name='invitationstatus'), autoincrement=False, nullable=False),
    sa.Column('invited_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('supplier_invitations_supplier_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('supplier_invitations_pkey'))
    )
    op.create_index(op.f('ix_supplier_invitations_invite_token'), 'supplier_invitations', ['invite_token'], unique=True)
    op.create_table('supplier_responses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('po_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('response_type', postgresql.ENUM('accepted', 'rejected', 'counter_offer', 'partial_fulfillment', name='responsetype'), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('counter_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('original_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('available_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ordered_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('responded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('supplier_responses_po_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('supplier_responses_pkey'))
    )
    op.create_table('supplier_users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('admin', 'staff', name='supplieruserrole'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('must_change_password', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('invited_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('supplier_users_supplier_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('supplier_users_pkey'))
    )
    op.create_index(op.f('ix_supplier_users_email'), 'supplier_users', ['email'], unique=True)
    op.create_table('supplier_invoices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('po_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'submitted', 'under_review', 'approved', 'rejected', 'paid', 'partially_paid', name='invoicestatus'), autoincrement=False, nullable=False),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tax_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('match_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('match_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('review_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('supplier_invoices_po_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('supplier_invoices_supplier_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('supplier_invoices_pkey'))
    )
    op.create_index(op.f('ix_supplier_invoices_invoice_number'), 'supplier_invoices', ['invoice_number'], unique=True)
    # ### end Alembic commands ###
